In [1]:
import numpy as np

In [2]:
np.random.randint(1, 10)

1

In [3]:
np.random.ranf(5)

array([0.0536056 , 0.79590468, 0.0409151 , 0.85058777, 0.22077738])

In [4]:
np.random.normal(100, 20, 5) # μ, σ^2, number of samples to generate

array([107.23365377,  89.32370874,  84.61588101,  77.3057765 ,
       106.84714603])

In [5]:
np.random.binomial(500, 0.3, 5) # n, p, number of samples to generate

array([149, 144, 159, 139, 135])

In [6]:
np.random.poisson(100, 5) # λ, number of samples to generate

array([ 92, 108,  96, 101,  98])

In [7]:
np.mean(np.random.poisson(100, 5)) # mean

97.4

In [8]:
np.median(np.random.poisson(100, 5)) # median

111.0

In [9]:
np.var(np.random.poisson(100, 5)) # variance

183.6

In [10]:
np.std(np.random.poisson(100, 5)) # standard deviation

5.291502622129181

In [11]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.concatenate((a,b))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [14]:
c = np.arange(20)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
d = np.arange(0, 20, 2)
d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
e = np.empty(5)
e

array([5.24e-322, 4.55e-322, 4.59e-322, 4.64e-322, 4.94e-322])

In [17]:
np.linspace(0, 10, num=15) # start value, end value, number of values in the array

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [18]:
f = np.arange(20)
print(f)
print(f.shape)
f = f.reshape(4, 5) # product of the parameters should equate to the product of the original dimension
print(f)
f.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


(4, 5)

In [19]:
g = [1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,3]
np.unique(g, return_index=True, return_counts=True) 
# original list, 
# return_index returns index of the first occurance of each value in the list, 
# return_counts returns the total occurance of each value

(array([1, 2, 3, 4]), array([ 0,  4,  8, 12]), array([4, 4, 5, 3]))

In [23]:
g = [[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]]
np.unique(g, axis=0) 
# axis = 0 returns unique rows. if not specified np.unique treats any dimensional array as 1d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [28]:
np.flip(g)

array([[15, 14, 13],
       [12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [31]:
np.flip(g, axis=0)

array([[13, 14, 15],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [32]:
np.flip(g, axis=1)

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10],
       [15, 14, 13]])