In [1]:
import numpy as np

In [ ]:
board = []
for i in range(9):
    board.append([])
    for j in range(9):
        v = input()
        board[i].append(int(v))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
8
4
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [4]:
def check(y,x,n):
    global board
    for i in range(0,9):
        if board[y][i] == n:
            return False
    for i in range(0,9):
        if board[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if board[y0 + i][x0 + j] == n:
                return False
    return True

In [5]:
def final() :
    global board
    for y in range(9) :
        for x in range(9) :
            if board[y][x] == 0 :
                for n in range(1,10) :
                    if check(y,x,n) :
                        board[y][x] = n
                        final()
                        board[y][x] = 0
                return
    print(np.matrix(board))
    input('More?')

In [8]:
final()

[[5 8 6 2 3 1 4 7 9]
 [4 3 7 8 9 5 1 6 2]
 [9 1 2 4 6 7 5 3 8]
 [6 2 9 1 7 8 3 4 5]
 [1 5 8 9 4 3 7 2 6]
 [3 7 4 6 5 2 8 9 1]
 [8 6 5 7 2 4 9 1 3]
 [2 4 3 5 1 9 6 8 7]
 [7 9 1 3 8 6 2 5 4]]
More?
